[libraries]
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version = "0.33.2-alpha" }
accompanist-swiperefresh = { group = "com.google.accompanist", name = "accompanist-swiperefresh", version = "0.33.2-alpha" }
accompanist-insets = { group = "com.google.accompanist", name = "accompanist-insets", version = "0.31.5-beta" }
engage-core = { group = "com.google.android.engage", name = "engage-core", version = "1.3.1" }
[versions]